# Site settings
title:          Hersh Bhasin's Blog
description:    "Hersh Bhasin's Writings"
#baseurl:        "/tale"
url:            "https://blog.harshbhasin.com"

# Google Analytics
google_analytics: UA-141374393-1

# Author
author:
  name:         Hersh Bhasin
  url:          https://blog.hershbhasin.com
  email:        hershbhasin63@gmail.com

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       10

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]
